### ISSUE TITLE
[Enhancement] : Can you push updated csv with label here ?

### ISSUE THREAD

**Issue by VinayChaudhari1996** [Savjee/yt-spam-classifier#1]
Hi Savejee,

Great Work! Really Appreciated 

Can you auto-push the latest labels CSV on git?

Thanks

**Comment by Savjee** [comment]
Hi,

Here's the Google Spreadsheet that I currently use: https://docs.google.com/spreadsheets/d/1QEQrLne1SDxwQVl5qpGQokEKG4FNZqX6kMuFMmAyeWg/edit?usp=sharing

I go over the comments there about once a month.
Closing this issue, but feel free to ask additional questions.

**Comment by VinayChaudhari1996** [comment]
Thanks Man , will contribute in it 👍
